[[hosts]]
name = "server-01"
ip = "admin@192.168.1.101"

[[hosts]]
name = "server-02"
ip = "admin@192.168.1.102"

[[hosts]]
name = "server-03"
ip = "admin@192.168.1.103"

[[hosts]]
name = "server-04"
ip = "admin@192.168.1.104"

[[users]]
username = "admin_user"
password = "strongpassword456"
groups = ["admin"]
